# Generated by Django 4.2.7 on 2023-11-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_quantity',
        ),
    ]
